#!/usr/bin/env bash
set -euo pipefail

if [[ ${1:-} == "-d" ]]; then
  sel=$(tv dirs)
else
  sel=$(tv files)
fi

[[ -z ${sel:-} ]] && exit 0

rel=$(realpath --relative-to="$PWD" "$sel")
tmux send-keys -l -t "${FM_PANE:?FM_PANE not set}" -- "$rel"
