--when.repositories = ["~/forks"]

[remotes]
origin.auto-track-bookmarks = "*"
upstream.auto-track-bookmarks = "aamini/*"
upstream.fetch-bookmarks = "main"

[revsets]
log = 'builtin_log() & ~(mutable() & ~mine()) | (::main ~ ::main@upstream) | (parents(merges() & ::main) & tags()) | all_work()'

[revset-aliases]
"trunk()" = "main@origin"
