[ui.colors]
"selected" = { bg = "#313244" }

[revisions]
revset = "daily()"

[preview]
position = "bottom"
revision_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  'jj show --color always -r "$1"',
  "jjui-preview",
  "$change_id",
]
oplog_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  'jj op show "$1" --color always',
  "jjui-preview",
  "$operation_id",
]
file_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  'jj diff --color always -r "$1" -- "$2"',
  "jjui-preview",
  "$change_id",
  "$file",
]
